image:
  repository: ghcr.io/theroyallab/tabbyapi
  tag: latest
  pullPolicy: IfNotPresent

model:
  name: ""
  repo: ""
  revision: ""

config:
  maxSeqLen: 4096
  cacheSize: 4096
  cacheMode: FP16
  gpuSplitAuto: true

shmSize: 512Mi

resources:
  requests:
    cpu: 2
    memory: 2Gi
  limits:
    memory: 4Gi

service:
  port: 5000

persistence:
  size: 5Gi
  accessModes:
    - ReadWriteOnce
