environments:
  vllm-apple:
    values:
      - values/vllm-apple.yaml
      - environments/vllm.yaml
  
  llamacpp-apple:
    values:
      - environments/llamacpp.yaml

  vllm-nvidia:
    values:
      - values/vllm-nvidia.yaml
      - environments/vllm.yaml

  amd:
    values:
      - environments/llamacpp.yaml

  tabbyapi:
    values:
      - environments/tabbyapi.yaml

---

values:
  - vllm:
      enabled: false
  - tabbyapi:
      enabled: false
  - llamacpp:
      enabled: false

repositories:
  - name: vllm
    url: https://vllm-project.github.io/production-stack

releases:
  - name: vllm
    namespace: llm
    createNamespace: true
    condition: vllm.enabled
    chart: vllm/vllm-stack
    version: 0.1.12
    values:
      - values/vllm.yaml.gotmpl

  - name: vllm-service-access
    namespace: llm
    condition: vllm.enabled
    chart: ./charts/service-access
    values:
      - values/{{ .Environment.Name }}.yaml


  - name: tabbyapi
    namespace: llm
    createNamespace: true
    chart: ./charts/tabbyapi
    condition: tabbyapi.enabled
    values:
      - values/tabbyapi.yaml

  - name: tabbyapi-service-access
    namespace: llm
    condition: tabbyapi.enabled
    chart: ./charts/service-access
    values:
      - values/tabbyapi.yaml

  - name: llamacpp
    namespace: llm
    createNamespace: true
    condition: llamacpp.enabled
    chart: ./charts/llamacpp
    values:
      - values/llamacpp.yaml
      - values/{{ .Environment.Name }}.yaml

  - name: llamacpp-service-access
    namespace: llm
    condition: llamacpp.enabled
    chart: ./charts/service-access
    values:
      - values/llamacpp.yaml
